### ISSUE TITLE
Unable to reproduce the results

### ISSUE THREAD

**Issue by SupritYoung** [kevinscaria/InstructABSA#11]
Hello, I was not able to reproduce your results since your data is not open-sourced. I have transformed the data following the format you requested in your README, as shown in the attached image.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/30597946/235855834-446e21ad-e546-4702-829b-121bc0850d57.png">

However, the results I obtained were far from the results reported in your paper. Would it be possible for you to open-source the data or help point out if there is any mistake in the data format transformation that might have caused this issue?

<img width="630" alt="image" src="https://user-images.githubusercontent.com/30597946/235855872-366b09f1-f69e-46b2-b93e-48a94bb6050a.png">

**Comment by kevinscaria** [comment]
Dataset uploaded to the [folder](https://github.com/kevinscaria/InstructABSA/tree/main/Dataset) and the notebook to reproduce results is [here](https://github.com/kevinscaria/InstructABSA/blob/main/Notebooks/reproduce_results_notebook.ipynb).
