### ISSUE TITLE
Missing create_data_in_joint_task_format method at DatasetLoader

### ISSUE THREAD

**Issue by noshaq** [kevinscaria/InstructABSA#16]
Hi. Thanks for sharing the code of your papers.

I'm trying to reproduce the training for the joint task, but this error appears:
AttributeError: 'DatasetLoader' object has no attribute 'create_data_in_joint_task_format'
There is any way to solve it with the other methods in the class?

Thanks!

**Comment by kevinscaria** [comment]
Hi, 
There has been some API changes. I have not updated the run_model.py script yet. But for joint task, it should be:

create_data_in_aspe_format()

From here on joint task will be called as ASPE (Aspect Sentiment Pair Extraction), since new tasks are being added.

**Comment by noshaq** [comment]
Great! Thanks for your answer.
