### ISSUE TITLE
Are the checkpoints missing?

### ISSUE THREAD

**Issue by Skipper91** [kevinscaria/InstructABSA#2]
Hey there. I am not that sure, how to load the model for inference. Is it possible that the model checkpoints are missing? 

Greetings from Germany! :D

**Comment by kevinscaria** [comment]
Hey, I'll be adding the model checkpoints at Huggingface in a day or two. This repo is WIP. But I should be done in 2-3 days max.

**Comment by Skipper91** [comment]
Ok. Cool :) Thanks for the reply!

**Comment by kevinscaria** [comment]
The model checkpoints are uploaded to huggingface. You can use any one of them w.r.t your use case. Let me know if any other issue persists.
Best, 
Kevin
