### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by cheemsbaby** [kevinscaria/InstructABSA#4]
Hello!
May I share your data set? I want to try to reproduce the experimental data in your paper. If I can, I will be very grateful！

**Comment by kevinscaria** [comment]
Hello,
Sure give me few days. I’ve not mid terms going on. I’ll share it after that.

thanks.

**Comment by SupritYoung** [comment]
Hello! How about your mid terms ? I also wanna to share your dataset. I construct the dataset according to your format from SemEval, but the performance is not well as your paper. Thank you !

**Comment by kevinscaria** [comment]
Dataset uploaded to the [folder](https://github.com/kevinscaria/InstructABSA/tree/main/Dataset) and the notebook to reproduce results is [here](https://github.com/kevinscaria/InstructABSA/blob/main/Notebooks/reproduce_results_notebook.ipynb).
