### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by billy-mosse** [kevinscaria/InstructABSA#5]
Hi! Great repo :). Would you mind adding instructions on how to make this work?

For example, a `requirements.txt` file specifying which versions each library should have, and the python version.

I can help you if you don't know how to do it.

Thank you!

**Comment by kevinscaria** [comment]
Hi @billy-mosse , 
The repository is easy to implement. I have added all steps. I have pushed requirements.txt file. let me know if you are stuck anywhere.

Best,
KJS
